config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end

  namespace 'users' do
    resources :users, only: [:edit, :update]
  end

  # resource :barcodes
  get 'barcodes/index'
  get 'barcodes/show'

  namespace 'admins' do
    resources :categories, only:[:index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barcode.rb
class Barcode < ApplicationRecord
    
    require 'barby'
    require 'barby/barcode/ean_13'
    require 'barby/barcode/ean_8'
    require 'barby/outputter/png_outputter'
    
    belongs_to :user

    def initialize(number, type = :ean_13)
      @number = number.to_s
      @type = type
    end

  # PNG形式でデータURIスキームを生成
    def to_png_image
      'data:image/png;base64, ' + Base64.encode64(Barby::PngOutputter.new(barcode(@type, @number)).to_png)
    end

    private
    def barcode(type, data)
      case type
      when :ean_13 # 13桁の場合
        Barby::EAN13.new(data)
      when :ean_8 # 8桁の場合
        Barby::EAN8.new(data)
      end
    end
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController

  def index
     @barcode = Barcode.new(490333304734)
  end

  def show
    @number = 290000000000 + current_user.id
    @barcode = Barcode.new(@number)
  end


end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/views/barcodes/index.html.erb
<div class="container">
    <div class="row">
        <h1 id="barcode">Barcode is it!</h1></br></br>
        <body>
            <header class="full">
                <h1 class="h1">barcode</h1>
            </header>
            <section>barcode</section>          
            <iframe width="400" height="315" src="https://www.youtube.com/embed/wc-4MnU67Hk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            
        </body>
        <%= image_tag @barcode.to_png_image, id: 'barcode' %>
        <%= image_tag @barcode.to_png_image, id: 'barcode' %> 
        <%= image_tag @barcode.to_png_image, id: 'barcode' %> 
    </div>
</div>

app/views/barcodes/show.html.erb
<div class="container">
    <div class="row">
        <h3><%= current_user.name %>様会員証</h3></br></br>
        <div class="memberno">
            MemberNo.
            <%= current_user.id %>
        </div>
        <%= image_tag @barcode.to_png_image %></br></br>
        <%= link_to "編集", edit_users_user_path(current_user.id), class: "btn btn-primary" %>
    </div>
</div>