config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end

  namespace 'users' do
    resources :users, only: [:edit, :update]
  end

  # resource :barcodes
  get 'barcodes/index'
  get 'barcodes/show'

  namespace 'admins' do
    resources :categories, only:[:index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barcode.rb
class Barcode < ApplicationRecord
    
    require 'barby'
    require 'barby/barcode/ean_13'
    require 'barby/barcode/ean_8'
    require 'barby/outputter/png_outputter'
    
    belongs_to :user

    def initialize(number, type = :ean_13)
      @number = number.to_s
      @type = type
    end

  # PNG形式でデータURIスキームを生成
    def to_png_image
      'data:image/png;base64, ' + Base64.encode64(Barby::PngOutputter.new(barcode(@type, @number)).to_png)
    end

    private
    def barcode(type, data)
      case type
      when :ean_13 # 13桁の場合
        Barby::EAN13.new(data)
      when :ean_8 # 8桁の場合
        Barby::EAN8.new(data)
      end
    end
end

app/models/category_large.rb
class CategoryLarge < ApplicationRecord
  has_many :category_mediums, dependent: :destroy


end

app/models/category_medium.rb
class CategoryMedium < ApplicationRecord
  belongs_to :category_large

end

app/models/user.rb
class User < ApplicationRecord
  has_many :barcodes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/controllers/admins/admins_controller.rb
class Admins::AdminsController < ApplicationController
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        case resource
        when User
            barcodes_show_path
        when Admin
            barcodes_index_path
        end
    end

    def after_sign_out_path_for(resource)
        # byebug
        case resource
        when :user
            barcodes_index_path
        when :admin
            barcodes_index_path
        end
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController

  def index
     @barcode = Barcode.new(490333304734)
  end

  def show
    @number = 290000000000 + current_user.id
    @barcode = Barcode.new(@number)
  end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to barcodes_show_path
  end
    
    
  private
  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>member card</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap');
    </style>
  </head>

  <body>
    <header>
      <div class="container">
        <nav class="navbar navbar-fixed-top navbar-inverse">
          <button href="" class="nnavbar-toggler" data-toggle="collapse" data-target="#menu"><%= image_tag "barcode_illust.jpg", size: "30x30" %></button>

          <div id="menu" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Home", barcodes_index_path, {class: "glyphicon glyphicon-home home"} %></li>
                <li><%= link_to "ラーメンショップ", barcodes_index_path, {class: "glyphicon glyphicon-cutlery cutlery"} %></li>
                <li><%= link_to "投稿", barcodes_index_path, {class: "glyphicon glyphicon-flash flash"} %></li>
                <li><%= link_to "投稿一覧", barcodes_index_path, {class: "glyphicon glyphicon-book book"} %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out log-out" %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to "分類", barcodes_index_path, {class: "glyphicon glyphicon-home home"} %></li>
                <li><%= link_to "ラーメンショップ", barcodes_index_path, {class: "glyphicon glyphicon-cutlery cutlery"} %></li>
                <li><%= link_to "ユーザー", barcodes_index_path, {class: "glyphicon glyphicon-book book"} %></li>
                <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "glyphicon glyphicon-log-out log-out" %></li>
              <% else%>
                <li><%= link_to "Home", barcodes_index_path, {class: "glyphicon glyphicon-home home"} %></li>
                <li><%= link_to "ログイン", new_user_session_path, {class: "glyphicon glyphicon-log-in log-in"} %></li>
                <li><%= link_to "サインアップ", new_user_registration_path, {class: "glyphicon glyphicon-log-in log-in"} %></li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight BarcodeApp</p>
    	</div>
    </footer>
  </body>
</html>